version: '3'
services:
  mongodb-server:
    image: mongo:latest
    container_name: mongodb-server
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

  md-to-pdf:
    build: 
      context: ./services/md-to-pdf
    container_name: md-to-pdf-service
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  manim-renderer:
    build:
      context: ./services/manim-renderer
    container_name: manim-renderer-service
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - manim-temp:/app/temp
      - manim-output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongo-data:
  minio-data:
  qdrant-data:
  manim-temp:
  manim-output: