FROM ghcr.io/puppeteer/puppeteer:latest

# Switch to root for installation
USER root

WORKDIR /app

COPY . .

ARG PORT
ENV PORT=${PORT}

RUN npm install

EXPOSE ${PORT}

RUN npm run build

# Switch back to pptruser for running the app
USER pptruser

CMD [ "npm", "start" ]