"""Prompts module."""

from .prompts import (
    CONTENT_RESEARCHER_PROMPT,
    WORKSHEET_GENERATOR_PROMPT,
    DOUBT_SOLVER_PROMPT,
    ROUTER_PROMPT
)

__all__ = [
    "CONTENT_RESEARCHER_PROMPT",
    "WORKSHEET_GENERATOR_PROMPT",
    "DOUBT_SOLVER_PROMPT",
    "ROUTER_PROMPT"
]
